### ISSUE TITLE
ERROR - signalbox: Unable to update state.

### ISSUE THREAD

**Issue by aferrari-technisys** [cfreeman/signalbox#3]
Hi! i'm trying to use your implementation with bem.tv P2P streaming software... but i got errors about update status and can't share the connection between the peers

Logs here: http://pastebin.com/zgCpqXcw

Some advice to see what can be the issue?

Thanks

**Comment by cfreeman** [comment]
Looks like i have a little work to bring it up to speed with the latest version of rtc-quickconnect used by bem.tv

**Comment by cfreeman** [comment]
Give master another whirl, a couple of fixes should help. Got it passing all the signallercheck tests again -- https://github.com/rtc-io/rtc-signallercheck

**Comment by cdgraff** [comment]
I test latest release, and got this errors, i think is the same.

2015/06/12 17:15:35 INFO - Started SignalBox
2015/06/12 17:15:44 INFO - Serving primus.js file.
2015/06/12 17:15:46 Recieved "/announce|{\"id\":\"d26df57e-0062-4e99-b779-1d2eef6ad624\"}|{\"browser\":\"chrome\",\"browserVersion\":\"43.0.2357\",\"id\":\"d26df57e-0062-4e99-b779-1d2eef6ad624\",\"agent\":\"signaller@2.5.1\",\"room\":\"aHR0cDovLzE0OS4yNTUuMzcuMjI6ODA4MS9saXZlLzEzMGZEMThTZks3cHJKcnZVQXR1L3BsYXlsaXN0Lm0zdTg=\"}" from 0xc208096000
2015/06/12 17:16:06 INFO - Serving primus.js file.
2015/06/12 17:16:07 Recieved "/announce|{\"id\":\"fda6be29-ba79-47ec-ae3f-9e1ea8ab9322\"}|{\"browser\":\"chrome\",\"browserVersion\":\"43.0.2357\",\"id\":\"fda6be29-ba79-47ec-ae3f-9e1ea8ab9322\",\"agent\":\"signaller@2.5.1\",\"room\":\"aHR0cDovLzE0OS4yNTUuMzcuMjI6ODA4MS9saXZlLzEzMGZEMThTZks3cHJKcnZVQXR1L3BsYXlsaXN0Lm0zdTg=\"}" from 0xc2080960f0
2015/06/12 17:16:11 Recieved "primus::ping::1434122159931" from 0xc208096000
2015/06/12 17:16:21 ERROR - messagePump: Can't read from 0xc208096000, closing
2015/06/12 17:16:21 websocket: close 1005
2015/06/12 17:16:21 ERROR - signalbox: Unable to update state.
2015/06/12 17:16:21 Unable to close - no Peer matching socket.
2015/06/12 17:16:22 Recieved "/announce|{\"id\":\"d26df57e-0062-4e99-b779-1d2eef6ad624\"}|{\"browser\":\"chrome\",\"browserVersion\":\"43.0.2357\",\"id\":\"d26df57e-0062-4e99-b779-1d2eef6ad624\",\"agent\":\"signaller@2.5.1\",\"room\":\"aHR0cDovLzE0OS4yNTUuMzcuMjI6ODA4MS9saXZlLzEzMGZEMThTZks3cHJKcnZVQXR1L3BsYXlsaXN0Lm0zdTg=\"}" from 0xc2080961e0
2015/06/12 17:16:23 ERROR - messagePump: Can't read from 0xc2080961e0, closing
2015/06/12 17:16:23 websocket: close 1005
2015/06/12 17:16:23 ERROR - signalbox: Unable to update state.
2015/06/12 17:16:23 Unable to close - no Peer matching socket.
2015/06/12 17:16:23 Recieved "/announce|{\"id\":\"d26df57e-0062-4e99-b779-1d2eef6ad624\"}|{\"browser\":\"chrome\",\"browserVersion\":\"43.0.2357\",\"id\":\"d26df57e-0062-4e99-b779-1d2eef6ad624\",\"agent\":\"signaller@2.5.1\",\"room\":\"aHR0cDovLzE0OS4yNTUuMzcuMjI6ODA4MS9saXZlLzEzMGZEMThTZks3cHJKcnZVQXR1L3BsYXlsaXN0Lm0zdTg=\"}" from 0xc208096000
2015/06/12 17:16:25 ERROR - messagePump: Can't read from 0xc208096000, closing
2015/06/12 17:16:25 websocket: close 1005
2015/06/12 17:16:25 ERROR - signalbox: Unable to update state.
2015/06/12 17:16:25 Unable to close - no Peer matching socket.

thanks
Ale

**Comment by cfreeman** [comment]
Ahhh. I see. Using signaller 2.5.1 which is quite old, but not as old as what signalbox was supporting. Not sure how much rtc-signalcheck will help with testing though. Digging through the commits there it looks like it matured for testing 3.0.0 (the next version after 2.5.1).

**Comment by cfreeman** [comment]
Have now created a branch dedicated to the older signaller@2.5.1 -- It looks like it is using a different version of primus.js. The head of that branch was tested against the demo-signaller at this commit -- https://github.com/rtc-io/demo-signaller/tree/e3e4a611747de3a6358b133da227a27223574b51 

Which I think is the closest match for what is rolling in bem.tv

**Comment by cdgraff** [comment]
Thanks for create this branch!!! can guide me how install this Branch with GO GET?

**Comment by cfreeman** [comment]
Sorry. I Don't think go get supports branches. You will need to git clone it manually into your GOPATH and use git branch signaller@2.5.1 to switch branches. Then just use go build to build signalbox.

**Comment by aferrari-technisys** [comment]
Hi, thanks! is working now! just take a look the logs, to see if all look good? i see this errors too

015/06/16 21:28:10 ERROR - messagePump: Can't read from 0xc2080ffa40, closing
2015/06/16 21:28:10 EOF
2015/06/16 21:28:10 ERROR - signalbox: Unable to update state.
2015/06/16 21:28:10 Unable to close - no Peer matching socket.

Full logs:

http://pastebin.com/0LfFX4H5

Thanks for take the time to made this compatible with bem.tv

**Comment by cfreeman** [comment]
I think this is related to sockets being left as CLOSE_WAIT (I probably haven't handled the time out case correctly). A new issue should be created around this soon.

Thanks.
